repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/AndersSteenNilsen/random__pre_commit_messages
    rev: 3fa3f84e4a8963156fb77ee350a0e97366863876
    hooks:
      - id: random-git-messsage
