-   id: auto-git-messsage
    name: Generate git message
    description: This hook trims trailing whitespace.
    entry: create_message
    language: python
    args: [--gpt-3-key=dummy]
    stages: [commit-msg]