-   id: random-git-messsage
    name: random git messsage
    description: git commit -m "random" will give you a random commit message
    entry: create_message
    language: python
    stages: [commit-msg]