repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
#   - repo: local
#     hooks:
#       - id: local-auto-git-messsage
#         name: Generate git message
#         description: This hook trims trailing whitespace.
#         entry: auto-git-messsage
#         language: python
#         types: [text]
#         stages: [commit-msg]

#   - repo: .
#     rev: master
#     hooks:
#       - id: auto-git-messsage
