[project]
name = "auto_git_message"
version = "0.1.0"
description = "Adding git messages automatically."
authors = [
    "Anders Steen <asteennilsen@gmail.com>"
]
license = "MIT"
readme = "README.md"
python = "^3.7"
#homepage = "https://github.com/MartinThoma/infer_pyproject"
#repository = "https://github.com/MartinThoma/infer_pyproject"
#documentation = "https://github.com/MartinThoma/infer_pyproject"

keywords = ["pre-commit", "commit", "git"]

classifiers = [
    "Topic :: Software Development"
]

# Requirements
# [dependencies]
# pre-commit = "^7.0"

[dev-dependencies]
black = { version = "^22.3.0" }


[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"